# Generated by Django 4.2 on 2023-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_shipment_label_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Label'),
        ),
    ]
