# Generated by Django 4.2 on 2023-04-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Label'),
        ),
    ]
