# Generated by Django 4.2 on 2023-04-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('form_weight', models.PositiveIntegerField(verbose_name='form Weight')),
                ('to_weight', models.PositiveIntegerField(verbose_name='To Weight')),
                ('packging_weight', models.PositiveIntegerField(verbose_name='Packging Weight')),
                ('height', models.PositiveIntegerField(verbose_name='Height')),
                ('width', models.PositiveIntegerField(verbose_name='Width')),
                ('depth', models.PositiveIntegerField(verbose_name='Depth')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='height',
            field=models.PositiveIntegerField(default=1, verbose_name='Height'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.PositiveIntegerField(default=1, verbose_name='width'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Packaging_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('prevalance', models.PositiveIntegerField(verbose_name='Prevalance')),
                ('packaging_types', models.ManyToManyField(to='orders.packing_types')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='packaging_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.packaging_group'),
        ),
    ]
